/*
    Find a problem at projecteuler.net then create the solution. Add a comment beneath your solution that 
    includes a description of the problem. Upload your solution to github. Tweet me a link to your solution.

    Pentagonal numbers - Problem 44
    Pentagonal numbers are generated by the formula, P_n = n(3n - 1)/2. The first ten pentagonal numbers are:

        1, 5, 12, 22, 35, 51, 70, 92, 117, 145,...
    
    It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, the difference, 70 - 22 = 48, is not pentagonal. 

    Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and 
    D = |P_k - P_j| is minimised; what is the value of D?
*/

/*
    Solution:

    To find D we need to find the values of k and j such that the absolute difference between P_k and P_j 
    is the smallest it could while satisfying P_k + P_j = P_x and P_k - P_j = P_y for some x, y in 
    the natural numbers.

    Observation 1:

    Since 
*/